module.exports = {
    emailPattern: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
    urlPattern: /^(https?:\/\/)?([\da-z.-]+)\.([a-z.]{2,6})([\/\w .-]*)*\/?$/,
    phonePattern: /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/,
    datePattern: /^\d{4}-\d{2}-\d{2}$/,
    ipPattern: /^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/,
    hexColorPattern: /^#?([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$/,
    passwordPattern: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/,
    zipCodePattern: /^\d{5}(-\d{4})?$/,
    lettersPattern: /^[a-zA-Z]+$/,
    numbersPattern: /^\d+$/,
    ssnPattern: /^\d{3}-\d{2}-\d{4}$/,
    timePattern: /^([01]\d|2[0-3]):([0-5]\d)$/,
    positiveIntegerPattern: /^[1-9]\d*$/,
    negativeIntegerPattern: /^-[1-9]\d*$/,
    integerPattern: /^-?[1-9]\d*$/,
    decimalPattern: /^-?\d+(\.\d+)?$/,
    alphanumericPattern: /^[a-zA-Z0-9]+$/,
    whitespacePattern: /^\s+$/,
    noWhitespacePattern: /^\S+$/,
    htmlTagPattern: /^<\/?[\w\s="/.':;#-\/\?]+>$/i,
    creditCardPattern: /^\d{4}-?\d{4}-?\d{4}-?\d{4}$/,
    macAddressPattern: /^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$/,
    stateAbbreviationPattern: /^(A[LKZR]|C[AOT]|D[EC]|FL|GA|HI|I[ADLN]|K[SY]|LA|M[ADEHINOPST]|N[CDEHJMVY]|O[HKR]|P[ARW]|RI|S[CD]|T[NX]|UT|V[AIT]|W[AIVY])$/,
    hexColorWithAlphaPattern: /^#?([a-fA-F0-9]{8}|[a-fA-F0-9]{4})$/,
    htmlOpeningTagPattern: /^<([a-z]+)([^<]+)*(?:[^<]*[^\/])?>$/i,
    htmlClosingTagPattern: /^<\/([a-z]+)>$/i,
    htmlSelfClosingTagPattern: /^<([a-z]+)([^<]+)*\/>$/i,
    currencyPattern: /^\$?\d+(,\d{3})*(\.\d{2})?$/,
    markdownLinkPattern: /^\[([^\]]+)\]\(([^)]+)\)$/,
    base64Pattern: /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/,
    youtubeUrlPattern: /^https?:\/\/(www\.)?(youtube\.com|youtu\.be)\/(watch\?v=|embed\/|v\/|.+\?v=)?([^&=%\?]{11})$/,
    uuidPattern: /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,
    jsonStringPattern: /^(?:(true|false|null)|-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?|"(?:\\["\\\/bfnrt]|\\u[0-9a-fA-F]{4}|[^"\\])*"|\[.*\]|\{.*\})$/,
    domainNamePattern: /^(?!:\/\/)([a-zA-Z0-9-_]+(\.[a-zA-Z0-9-_]+)+)$/i,
    htmlCommentPattern: /<!--(.*?)-->/,
    unixFilePathPattern: /^(\/[^\/ ]*)+\/?$/,
    windowsFilePathPattern: /^[a-zA-Z]:\\(?:[^\\\/:*?"<>|\r\n]+\\)*[^\\\/:*?"<>|\r\n]*$/,
    rgbColorPattern: /^rgb\((\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3})\)$/,
    rgbaColorPattern: /^rgba\((\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3}),\s*(0|1|0?\.\d+)\)$/,
    cssVariablePattern: /^--[a-zA-Z0-9-_]+$/,
    slugPattern: /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
    htmlEntityPattern: /&[a-zA-Z0-9#]+;/,
    usernamePattern: /^[a-zA-Z0-9._-]{3,16}$/,
    creditCardCVVPattern: /^\d{3,4}$/,
    mimeTypePattern: /^[a-zA-Z0-9]+\/[a-zA-Z0-9\-.+]+$/,
    latitudePattern: /^-?([1-8]?[1-9]|[1-9]0)\.{1}\d{1,6}$/,
    longitudePattern: /^-?(([-+]?)([\d]{1,3})((\.)(\d+))?)$/,
    isbn10Pattern: /^(?:\d[\ |-]?){9}[\d|X]$/,
    isbn13Pattern: /^(?:\d[\ |-]?){13}$/,
    time24HourPattern: /^([01]\d|2[0-3]):([0-5]\d)$/,
    time12HourPattern: /^(1[0-2]|0?[1-9]):([0-5][0-9])([AP][M])$/,
    xmlTagPattern: /^<([a-zA-Z]+)(?:[^<]+)*(?:>(.*)<\/\1>|\s+\/>)$/,
    twitterHandlePattern: /^@?(\w){1,15}$/,
    hexadecimalPattern: /^#?([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$/,
    fileExtensionPattern: /\.([0-9a-z]+)(?=[?#])|(\.)(?:[\w]+)$/i,
    htmlAttributePattern: /^[a-zA-Z_:][-a-zA-Z0-9_:.]*$/,
    ssnWithDashesPattern: /^\d{3}-\d{2}-\d{4}$/,
    jsonDatePattern: /^\/Date\((\d+)([+-]\d{4})?\)\/$/,
    creditCardNumberPattern: /^4[0-9]{12}(?:[0-9]{3})?$/,
    strongPasswordPattern: /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*\W).{8,}$/,
    macAddressWithColonsPattern: /^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$/,
};
